# sonarqube-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: {{ .Values.sonarqube.image }}
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "512Mi"  # Adjust as needed
              cpu: "100m"       # Adjust as needed
            limits:
              memory: "1Gi"     # Adjust as needed
              cpu: "200m"       # Adjust as needed
          volumeMounts:
            - name: jdbc-driver
              mountPath: /opt/jdbc
          env:
            - name: SONARQUBE_JDBC_URL
              value: {{ .Values.sonarqube.jdbcUrl }}
            - name: SONARQUBE_JDBC_USERNAME
              value: {{ .Values.sonarqube.jdbcUsername }}
            - name: SONARQUBE_JDBC_PASSWORD
              value: {{ .Values.sonarqube.jdbcPassword }}
      volumes:
        - name: jdbc-driver
          configMap:
            name: jdbc-driver
